version: "3.8"

services:
  gitea:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITEA_USER_NAME: ${GITEA_USER_NAME}
        GITEA_USER_EMAIL: ${GITEA_USER_EMAIL}
        GITEA_USER_PASSWORD: ${GITEA_USER_PASSWORD}
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=${ROOT_URL}
      - DISABLE_REGISTRATION=false
      # Add any other Gitea environment variables here
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=gitea
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - cert:/etc/nginx/cert
    environment:
      - SERVER_NAME=${SERVER_NAME}
    ports:
      - "443:443"

  backup:
    image: busybox:latest
    volumes:
      - gitea-data:/data
      - ./setup:/setup
      - backup:/backup
    environment:
      - BACKUP_CRON_SCHEDULE=${BACKUP_CRON_SCHEDULE}
    command: sh -c "cp /setup/backup.sh /data && chmod +x /data/backup.sh && crond -f -l 8"

volumes:
  gitea-data:
  postgres-data:
  cert:
  backup:
